insert into item (itemName, itemRelease, itemWave, itemSeries, itemSeriesSubseries, itemRetailer, itemMedia, itemSeriesNumber, itemJPG) values 
('Boba Fett Tython','2021-11-01','{6}','Galaxy','','All Retailers','Star Wars: The Mandalorian','16','boba-fett-tython.jpg'),
('Fennec Shand','2021-11-01','{6}','Galaxy','','All Retailers','Star Wars: The Book of Boba Fett','1','fennec-shand.jpg'),
('Admiral Ackbar','2020-08-01','{1}','Galaxy','','All Retailers','Star Wars: Return of the Jedi','1','admiral-ackbar.jpg'),
('Clone Trooper Kamino','2020-08-01','{1}','Galaxy','','All Retailers','Star Wars: The Clone Wars','1','clone-trooper-kamino.jpg'),
('Imperial Stormtrooper Mandalorian','2020-08-01','{1}','Galaxy','','All Retailers','Star Wars: The Mandalorian','2','imperial-stormtrooper-mandalorian.jpg'),
('The Mandalorian (Beskar)','2020-08-01','{1}','Galaxy','','All Retailers','Star Wars: The Mandalorian','1','the-mandalorian-(beskar).jpg'),
('Phase I Clone Trooper','2020-11-01','{2}','Galaxy','','All Retailers','Star Wars: Attack of the Clones','2','phase-i-clone-trooper.jpg'),
('Han Solo Endor','2020-11-01','{2}','Galaxy','','All Retailers','Star Wars: Return of the Jedi','5','han-solo-endor.jpg'),
('Luke Skywalker Endor','2020-11-01','{2}','Galaxy','','All Retailers','Star Wars: Return of the Jedi','4','luke-skywalker-endor.jpg'),
('Princess Leia Organa Endor','2020-11-01','{2}','Galaxy','','All Retailers','Star Wars: Return of the Jedi','3','princess-leia-organa-endor.jpg'),
('Cad Bane','2020-11-01','{2}','Galaxy','','All Retailers','Star Wars: The Clone Wars','6','cad-bane.jpg'),
('Rebel Trooper Hoth','2020-11-01','{2}','Galaxy','','All Retailers','Star Wars: The Empire Strikes Back','3','rebel-trooper-hoth.jpg'),
('Incinerator Trooper','2020-11-01','{2}','Galaxy','','All Retailers','Star Wars: The Mandalorian','3','incinerator-trooper.jpg'),
('The Armorer','2020-12-01','"{2','3}"','Galaxy','','All Retailers','Star Wars: The Mandalorian','4','the-armorer.jpg'),
('Moff Gideon','2020-12-01','{3}','Galaxy','','All Retailers','Star Wars: The Mandalorian','8','moff-gideon.jpg'),
('Kuiil','2020-12-01','{3}','Galaxy','','All Retailers','Star Wars: The Mandalorian','7','kuiil.jpg'),
('Greef Karga','2020-12-01','{3}','Galaxy','','All Retailers','Star Wars: The Mandalorian','6','greef-karga.jpg'),
('Elite Squad Trooper','2021-04-01','{4}','Galaxy','','All Retailers','Star Wars: The Bad Batch','3','elite-squad-trooper.jpg'),
('Crosshair','2021-04-01','{4}','Galaxy','','All Retailers','Star Wars: The Bad Batch','2','crosshair.jpg'),
('Hunter','2021-04-01','{4}','Galaxy','','All Retailers','Star Wars: The Bad Batch','1','hunter.jpg'),
('Asajj Ventress','2021-04-01','{4}','Galaxy','','All Retailers','Star Wars: The Clone Wars','7','asajj-ventress.jpg'),
('Bo Katan Kryze','2021-04-01','"{4','5}"','Galaxy','','All Retailers','Star Wars: The Mandalorian','10','bo-katan-kryze.jpg'),
('Tech','2021-06-01','{5}','Galaxy','','All Retailers','Star Wars: The Bad Batch','4','tech.jpg'),
('Aurra Sing','2021-06-01','{5}','Galaxy','','All Retailers','Star Wars: The Clone Wars','8','aurra-sing.jpg'),
('Koska Reeves','2021-06-01','{5}','Galaxy','','All Retailers','Star Wars: The Mandalorian','12','koska-reeves.jpg'),
('Q9 0 Zero','2021-06-01','{5}','Galaxy','','All Retailers','Star Wars: The Mandalorian','11','q9-0-zero.jpg'),
('Stormtrooper Jedha Patrol','2021-11-01','{6}','Galaxy','','All Retailers','Rogue One: A Star Wars Story','9','stormtrooper-jedha-patrol.jpg'),
('Doctor Evazan','2021-11-01','{6}','Galaxy','','All Retailers','Star Wars: A New Hope','3','doctor-evazan.jpg'),
('Ponda Baba','2021-11-01','{6}','Galaxy','','All Retailers','Star Wars: A New Hope','2','ponda-baba.jpg'),
('Princess Leia Organa Yavin 4','2021-11-01','{6}','Galaxy','','All Retailers','Star Wars: A New Hope','1','princess-leia-organa-yavin-4.jpg'),
('Teebo','2020-08-01','{1}','Galaxy','','All Retailers','Star Wars: Return of the Jedi','2','teebo.jpg'),
('Migs Mayfeld Morak','2021-11-01','{6}','Galaxy','','All Retailers','Star Wars: The Mandalorian','15','migs-mayfeld-morak.jpg'),
('Echo','2022-04-01','{7}','Galaxy','','All Retailers','Star Wars: The Bad Batch','11','echo.jpg'),
('Omega','2022-04-01','{7}','Galaxy','','All Retailers','Star Wars: The Bad Batch','10','omega.jpg'),
('Death Watch Mandalorian','2022-04-01','{7}','Galaxy','','All Retailers','Star Wars: The Mandalorian','21','death-watch-mandalorian.jpg'),
('The Client','2022-04-01','{7}','Galaxy','','All Retailers','Star Wars: The Mandalorian','20','the-client.jpg'),
('Figrin Dan','2022-08-01','{8}','Galaxy','','All Retailers','Star Wars: A New Hope','4','figrin-dan.jpg'),
('Fifth Brother Inquisitor','2022-08-01','{8}','Galaxy','','All Retailers','Star Wars: Obi-Wan Kenobi','4','fifth-brother-inquisitor.jpg'),
('Reva Third Sister','2022-08-01','{8}','Galaxy','','All Retailers','Star Wars: Obi-Wan Kenobi','3','reva-third-sister.jpg'),
('Darth Vader','2022-08-01','{8}','Galaxy','','All Retailers','Star Wars: Obi-Wan Kenobi','2','darth-vader-obi-wan-kenobi.jpg'),
('Princess Leia Ewok Village','2022-08-01','{8}','Galaxy','','All Retailers','Star Wars: Return of the Jedi','9','princess-leia-ewok-village.jpg'),
('New Republic Security Droid','2022-08-01','{8}','Galaxy','','All Retailers','Star Wars: The Mandalorian','23','new-republic-security-droid.jpg'),
('Obi Wan Kenobi Wandering Jedi','2022-08-01','"{8','9}"','Galaxy','','All Retailers','Star Wars: Obi-Wan Kenobi','1','obi-wan-kenobi-wandering-jedi.jpg'),
('Darth Vader','2020-08-01','{1}','Galaxy','','All Retailers','Star Wars: The Empire Strikes Back','1','darth-vader-esb.jpg'),
('Antoc Merrick','2022-07-01','{}','Galaxy','','Target','Rogue One: A Star Wars Story','8','antoc-merrick.jpg'),
('Galen Erso','2022-07-01','{}','Galaxy','','Target','Rogue One: A Star Wars Story','7','galen-erso.jpg'),
('Fourth Sister Inquisitor','2099-01-01','{}','Galaxy','','All Retailers','Star Wars: Obi-Wan Kenobi','12','fourth-sister-inquisitor.jpg'),
('Bodhi Rook','2022-02-01','{}','Galaxy','','Fan Channel','Rogue One: A Star Wars Story','6','bodhi-rook.jpg'),
('Baze Malbus','2022-02-01','{}','Galaxy','','Fan Channel','Rogue One: A Star Wars Story','5','baze-malbus.jpg'),
('Chirrut Imwe','2022-02-01','{}','Galaxy','','Fan Channel','Rogue One: A Star Wars Story','4','chirrut-imwe.jpg'),
('K 2So','2022-02-01','{}','Galaxy','','Fan Channel','Rogue One: A Star Wars Story','3','k-2so.jpg'),
('Captain Cassian Andor','2022-02-01','{}','Galaxy','','Fan Channel','Rogue One: A Star Wars Story','2','captain-cassian-andor.jpg'),
('Jyn Erso','2022-02-01','{}','Galaxy','','Fan Channel','Rogue One: A Star Wars Story','1','jyn-erso.jpg'),
('13Th Battalion Trooper','2022-11-01','{}','Galaxy','Gaming Greats','GameStop','Star Wars Jedi: Fallen Order','12','13th-battalion-trooper.jpg'),
('Cal Kestis Deluxe','2022-05-01','{}','Galaxy','Gaming Greats','GameStop','Star Wars Jedi: Fallen Order','2','cal-kestis-deluxe.jpg'),
('Flametrooper','2021-08-01','{}','Galaxy','Gaming Greats','GameStop','Star Wars Jedi: Fallen Order','3','flametrooper.jpg'),
('Nightbrother Archer','2022-06-01','{}','Galaxy','Gaming Greats','GameStop','Star Wars Jedi: Fallen Order','10','nightbrother-archer.jpg'),
('Nightbrother Warrior','2022-03-01','{}','Galaxy','Gaming Greats','GameStop','Star Wars Jedi: Fallen Order','5','nightbrother-warrior.jpg'),
('B1 Battle Droid','2022-11-01','{}','Galaxy','Gaming Greats','GameStop','Star Wars Jedi: Survivor','16','b1-battle-droid-jedi-survivor.jpg'),
('Riot Scout Trooper','2022-11-01','{}','Galaxy','Gaming Greats','GameStop','Star Wars Jedi: Survivor','14','riot-scout-trooper.jpg'),
('Nalan Cheel Deluxe','2022-07-01','{}','Galaxy','','ShopDisney','Star Wars: A New Hope','5','nalan-cheel-deluxe.jpg'),
('Clone Trooper Lieutenant','2020-09-01','{}','Galaxy','','Walgreens','Star Wars: Attack of the Clones','1','clone-trooper-lieutenant.jpg'),
('Arc Trooper Umbra Operative','2022-05-01','{}','Galaxy','Gaming Greats','GameStop','Star Wars: Battlefront II','9','arc-trooper-umbra-operative.jpg'),
('Battlefront Ii Jet Trooper','2022-03-01','{}','Galaxy','Gaming Greats','GameStop','Star Wars: Battlefront II','6','battlefront-ii-jet-trooper.jpg'),
('Imperial Rocket Trooper','2021-06-01','{}','Galaxy','Gaming Greats','GameStop','Star Wars: Battlefront II','1','imperial-rocket-trooper.jpg'),
('Zaalbar','2021-10-01','{}','Galaxy','Gaming Greats','GameStop','Star Wars: Knights of the Old Republic','4','zaalbar.jpg'),
('Obi Wan Kenobi Jabiim','2099-01-01','{}','Galaxy','','All Retailers','Star Wars: Obi-Wan Kenobi','11','obi-wan-kenobi-jabiim.jpg'),
('Ned B Deluxe','2022-12-01','{}','Galaxy','','All Retailers','Star Wars: Obi-Wan Kenobi','10','ned-b-deluxe.jpg'),
('Boba Fett Rotj Deluxe','2021-03-01','{}','Galaxy','','All Retailers','Star Wars: Return of the Jedi','6','boba-fett-rotj-deluxe.jpg'),
('Bib Fortuna','2021-11-01','{6}','Galaxy','','All Retailers','Star Wars: Return of the Jedi','8','bib-fortuna.jpg'),
('1 Jac','2099-01-01','{}','Galaxy','','Walmart','Star Wars: Obi-Wan Kenobi','8','1-jac.jpg'),
('Purge Trooper Phase Ii Armor','2099-01-01','{}','Galaxy','','Walmart','Star Wars: Obi-Wan Kenobi','7','purge-trooper-phase-ii-armor.jpg'),
('Ben Kenobi Tibidon Station','2022-12-01','{}','Galaxy','','Target','Star Wars: Obi-Wan Kenobi','6','ben-kenobi-tibidon-station.jpg'),
('Teeka Jawa','2022-06-01','{}','Galaxy','','Target','Star Wars: Obi-Wan Kenobi','5','teeka-jawa.jpg'),
('Rc 1138 Boss','2022-03-01','{}','Galaxy','Gaming Greats','GameStop','Star Wars: Republic Commando','7','rc-1138-boss.jpg'),
('Rc 1140 Fixer','2022-11-01','{}','Galaxy','Gaming Greats','GameStop','Star Wars: Republic Commando','13','rc-1140-fixer.jpg'),
('Rc 1207 Sev','2022-08-01','{}','Galaxy','Gaming Greats','GameStop','Star Wars: Republic Commando','11','rc-1207-sev.jpg'),
('Wrecker Deluxe','2021-06-01','{}','Galaxy','','All Retailers','Star Wars: The Bad Batch','5','wrecker-deluxe.jpg'),
('Cad Bane Bracca','2022-07-01','{}','Galaxy','','Amazon','Star Wars: The Bad Batch','12','cad-bane-bracca.jpg'),
('Crosshair Imperial','2021-11-01','{}','Galaxy','','Walmart','Star Wars: The Bad Batch','9','crosshair-imperial.jpg'),
('Vice Admiral Rampart','2021-11-01','{}','Galaxy','','Walmart','Star Wars: The Bad Batch','8','vice-admiral-rampart.jpg'),
('Imperial Clone Shock Trooper','2021-11-01','{}','Galaxy','','Walmart','Star Wars: The Bad Batch','7','imperial-clone-shock-trooper.jpg'),
('Clone Captain Rex','2021-11-01','{}','Galaxy','','Walmart','Star Wars: The Bad Batch','6','clone-captain-rex.jpg'),
('Aayla Secura','2022-11-01','{9}','Galaxy','','All Retailers','Star Wars: Attack of the Clones','3','aayla-secura.jpg'),
('Grand Inquisitor','2022-11-01','{9}','Galaxy','','All Retailers','Star Wars: Obi-Wan Kenobi','9','grand-inquisitor.jpg'),
('Clone Trooper 187Th Battalion','2022-11-01','{}','Galaxy','','Walgreens','Star Wars: The Clone Wars','10','clone-trooper-187th-battalion.jpg'),
('Clone Trooper 212Th Battalion','2022-04-01','{}','Galaxy','','Walgreens','Star Wars: The Clone Wars','9','clone-trooper-212th-battalion.jpg'),
('Darth Maul','2022-11-01','{9}','Galaxy','','All Retailers','Star Wars: The Clone Wars','11','Darth Maul.jpg'),
('Grogu','2022-11-01','{9}','Galaxy','','All Retailers','Star Wars: The Mandalorian','26','grogu.jpg'),
('Axe Woves','2022-11-01','{9}','Galaxy','','All Retailers','Star Wars: The Mandalorian','25','axe-woves.jpg'),
('Magistrate Greef Karga','2022-11-01','{9}','Galaxy','','All Retailers','Star Wars: The Mandalorian','24','magistrate-greef-karga.jpg'),
('Migs Mayfeld','2022-11-01','{9}','Galaxy','','All Retailers','Star Wars: The Mandalorian','27','migs-mayfeld.jpg'),
('Saw Gerrera Deluxe','2022-07-01','{}','Galaxy','','All Retailers','Rogue One: A Star Wars Story','10','saw-gerrera-deluxe.jpg'),
('Tala Imperial Officer','2099-01-01','{}','Galaxy','','All Retailers','Star Wars: Obi-Wan Kenobi','13','tala-imperial-officer.jpg'),
('Ahsoka Tano','2020-08-01','{}','Galaxy','','Fan Channel','Star Wars Rebels','7','ahsoka-tano.jpg'),
('Sabine Wren','2020-08-01','{}','Galaxy','','Fan Channel','Star Wars Rebels','6','sabine-wren.jpg'),
('Hera Syndulla','2020-08-01','{}','Galaxy','','Fan Channel','Star Wars Rebels','5','hera-syndulla.jpg'),
('Kanan Jarrus','2020-08-01','{}','Galaxy','','Fan Channel','Star Wars Rebels','4','kanan-jarrus.jpg'),
('Ezra Bridger','2020-08-01','{}','Galaxy','','Fan Channel','Star Wars Rebels','3','ezra-bridger.jpg'),
('Chopper','2020-08-01','{}','Galaxy','','Fan Channel','Star Wars Rebels','2','chopper.jpg'),
('Garazeb Zeb Orrelios Deluxe','2020-08-01','{}','Galaxy','','Fan Channel','Star Wars Rebels','1','garazeb-zeb-orrelios-deluxe.jpg'),
('Mandalorian Super Commando','2020-11-01','{}','Galaxy','','Walmart','Star Wars: The Clone Wars','5','mandalorian-super-commando.jpg'),
('Mandalorian Loyalist','2020-11-01','{}','Galaxy','','Walmart','Star Wars: The Clone Wars','4','mandalorian-loyalist.jpg'),
('332Nd Clone Trooper','2020-11-01','{}','Galaxy','','Walmart','Star Wars: The Clone Wars','3','332nd-clone-trooper.jpg'),
('Ahsoka Tano Clone Wars','2020-11-01','{}','Galaxy','','Walmart','Star Wars: The Clone Wars','2','ahsoka-tano-clone-wars.jpg'),
('The Mandalorian Grogu Maldo Kreis Deluxe','2022-10-01','{}','Galaxy','','Target','Star Wars: The Mandalorian','17','the-mandalorian-grogu-maldo-kreis-deluxe.jpg'),
('The Mandalorian And Grogu Arvala 7 Deluxe','2022-02-01','{}','Galaxy','','Target','Star Wars: The Mandalorian','14','the-mandalorian-and-grogu-arvala-7-deluxe.jpg'),
('Artillery Stormtrooper','2021-11-01','{}','Galaxy','','Amazon','Star Wars: The Mandalorian','13','artillery-stormtrooper.jpg'),
('Boba Fett Prototype','2022-09-01','{}','Galaxy','','Amazon','Star Wars: The Empire Strikes Back','4','boba-fett-prototype.jpg'),
('Luke Skywalker Snowspeeder','2020-08-01','{1}','Galaxy','','All Retailers','Star Wars: The Empire Strikes Back','2','luke-skywalker-snowspeeder.jpg'),
('Kx Security Droid Jedi Survivor','2022-11-01','{}','Galaxy','Gaming Greats','GameStop','Star Wars Jedi: Survivor','15','kx-security-droid-jedi-survivor.jpg'),
('Imperial Senate Guard','2022-04-01','{}','Galaxy','Gaming Greats','GameStop','Star Wars: The Force Unleashed','8','imperial-senate-guard.jpg'),
('Paz Vizsla','2022-03-01','{}','Galaxy','Carbonized','Target','Star Wars: The Mandalorian','','paz-vizsla-deluxe.jpg'),
('Scout Trooper','2022-03-01','{}','Galaxy','Carbonized','Target','Star Wars: The Mandalorian','','scout-trooper-carbonized.jpg'),
('Shoretrooper','2022-03-01','{}','Galaxy','Carbonized','Target','Star Wars: The Mandalorian','','shoretrooper-carbonized.jpg'),
('Rey Dark Side Vision','2020-12-01','{3}','Galaxy','','All Retailers','Star Wars: The Rise of Skywalker','1','rey-dark-side-vision.jpg'),
('The Armorer Deluxe','2021-10-01','{}','Galaxy','','Hasbro Pulse','Star Wars: The Mandalorian','','the-armorer-deluxe.jpg'),
('General Lando','2021-06-01','{5}','Galaxy','','All Retailers','Star Wars: Return of the Jedi','7','general-lando.jpg'),
('Ahsoka Tano','2022-04-01','{7}','Galaxy','','All Retailers','Star Wars: The Mandalorian','19','ahsoka-tano-corvus.jpg'),
('Boba Fett Throne Room Deluxe','2022-03-01','{}','Galaxy','','All Retailers','Star Wars: The Book of Boba Fett','2','boba-fett-throne-room-deluxe.jpg'),
('Boba Fett Tython Jedi Ruins Deluxe','2099-01-01','{}','Galaxy','','Walmart','Star Wars: The Mandalorian','22','boba-fett-tython-jedi-ruins-deluxe.jpg'),
('Remnant Stormtrooper','2021-01-01','{}','Galaxy','','Target','Star Wars: The Mandalorian','9','remnant-stormtrooper.jpg'),
('Din Djarin And The Child Deluxe','2020-12-01','{}','Galaxy','','Target','Star Wars: The Mandalorian','5','din-djarin-and-the-child-deluxe.jpg'),
('Jar Jar Binks Deluxe','2021-01-01','{}','Galaxy','','All Retailers','Star Wars: The Phantom Menace','1','jar-jar-binks-deluxe.jpg'),
('Rocket Launcher Trooper','2099-01-01','{}','Galaxy','Gaming Greats','GameStop','Star Wars Jedi: Fallen Order','21','rocket-launcher-trooper.jpg'),
('Battle Droid','2099-01-01','{}','Galaxy','Gaming Greats','GameStop','Star Wars: Republic Commando','18','battle-droid-18.jpg'),
('Darth Malak','2099-01-01','{11}','Galaxy','Gaming Greats','All Retailers','Star Wars: Knights of the Old Republic','19','darth-malak.jpg'),
('Bastila Shan','2099-01-01','{11}','Galaxy','Gaming Greats','All Retailers','Star Wars: Knights of the Old Republic','20','bastila-shan.jpg'),
('Cal Kestis','2099-01-01','{10}','Galaxy','Gaming Greats','All Retailers','Star Wars Jedi: Survivor','17','cal-kestis.jpg'),
('Din Djarin (Morak)','2099-01-01','{10}','Galaxy','','All Retailers','Star Wars: The Mandalorian','31','din-djarin-(morak).jpg'),
('Cobb Vanth Deluxe','2022-07-01','{}','Galaxy','','All Retailers','Star Wars: The Mandalorian','18','cobb-vanth-deluxe.jpg'),
('Speeder Bike Scout Trooper And The Child','2021-12-01','{}','Galaxy','','All Retailers','Star Wars: The Mandalorian','','speeder-bike-scout-trooper-and-the-child.jpg'),
('Luke Skywalker Imperial Light Cruiser','2099-01-01','{}','Galaxy','','All Retailers','Star Wars: The Mandalorian','30','luke-skywalker-imperial-light-cruiser.jpg'),
('Hk 87','2099-01-01','{}','Galaxy','','All Retailers','Star Wars: The Mandalorian','29','hk-87.jpg'),
('Dark Trooper Deluxe','2022-09-01','{}','Galaxy','','All Retailers','Star Wars: The Mandalorian','28','dark-trooper-deluxe.jpg'),
('The Mandalorian * Ahsoka Tano * Grogu','2022-10-01','{}','Galaxy','','Amazon','Star Wars: The Mandalorian','','the-mandalorian-ahsoka-tano-grogu.jpg'),
('Cassian Andor (Aldhani Mission)','2022-12-01','{}','Galaxy','','Walmart','Star Wars: Andor','1','cassian-andor-aldhani-mission.jpg'),
('Imperial Officer (Dark Times)','2022-12-01','{}','Galaxy','','Walmart','Star Wars: Andor','2','imperial-officer-(dark-times).jpg'),
('Shoretrooper','2022-12-01','{}','Galaxy','','Target','Star Wars: Andor','3','shoretrooper.jpg'),
('Imperial Officer (Ferrix)','2022-12-01','{}','Galaxy','','Target','Star Wars: Andor','4','imperial-officer-(ferrix).jpg'),
('Bix Caleen','2099-01-01','{10}','Galaxy','','All Retailers','Star Wars: Andor','5','bix-caleen.jpg'),
('Luthen Rael','2099-01-01','{10}','Galaxy','','All Retailers','Star Wars: Andor','6','luthen-rael.jpg'),
('Senator Mon Mothma','2099-01-01','{10}','Galaxy','','All Retailers','Star Wars: Andor','7','senator-mon-mothma.jpg'),
('Cassian Andor','2099-01-01','{10}','Galaxy','','All Retailers','Star Wars: Andor','8','cassian-andor-08.jpg'),
('Vel Sartha','2099-01-01','{11}','Galaxy','','All Retailers','Star Wars: Andor','9','vel-sartha.jpg'),
('Clone Commander Jesse','2099-01-01','{}','Galaxy','','Walmart','Star Wars: The Clone Wars','12','clone-commander-jesse.jpg'),
('Ned-B & Purge Trooper','2099-01-01','{}','Galaxy','Carbonized','Amazon','Star Wars: Obi-Wan Kenobi','','ned-b-&-purge-trooper.jpg'),
('Luke Skywalker & Grogu','2099-01-01','{}','Galaxy','','All Retailers','Star Wars: The Book of Boba Fett','3','luke-skywalker-&-grogu.jpg'),
('Scorch','2023-03-01','{}','Galaxy','Gaming Greats','GameStop','Star Wars: Republic Commando','18','scorch.jpg'),
('Krrsantan','2099-01-01','{}','Galaxy','','All Retailers','Star Wars: The Book of Boba Fett','4','krrsantan.jpg'),
('Cobb Vanth & Cad Bane','2099-01-01','{}','Galaxy','','Target','Star Wars: The Book of Boba Fett','','cobb-vanth-&-cad-bane.jpg'),
